sonata_admin:
  title: "MINESEC SUBVENTIONS"
  show_mosaic_button: false
  
  assets:
    extra_stylesheets:
      - admin/admin.css
    extra_javascripts:
      - admin/admin.js
  
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }

  options:
    list_action_button_content: icon

  security:
    handler: sonata.admin.security.handler.role

    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]